baseURL = "https://www.apanbapan.se/"
languageCode = "en-us"
title = "Apanbapan's musings"
theme = "after-dark"

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/" 
[[menu.main]]
  name = "Posts"
  weight = 2
  identifier = "post"
  url = "/post/"
[[menu.main]]
  name = "About"
  weight = 2
  identifier = "about"
  url = "/about/"